name: GET UP

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'weather message'
        required: false

jobs:
  sync:
    name: Build
    runs-on: ubuntu-latest
    steps:
     strategy:
        matrix:
         node-version: [12.x]
      steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
        npm install

      - name: GET UP
        run: |
          node index.js ${{ secrets.G_T }} weather_message
